import DarkModeButton from "@/components/modules/DarkModeButton";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`dark ${inter.className}`}>
      <body
        classNamclassName="dark"
        e={`${inter.variable} font-sans antialiased`}
      >
        {children}
        <section className="fixed bottom-9 right-6 z-50">
          <DarkModeButton />
        </section>
      </body>
    </html>
  );
}
